type SavedItem{
    id:ID!
    user_id:ID!
    item:String!
    description:String
    unitPrice:String
    uri:String
    image:String
    site:String
    rating:String
    dateCreated:String

}

type newItemInput{
    user_id:ID!
    item:String!
    description:String
    unitPrice:String
    uri:String
    image:String
    site:String
    rating:String
    dateCreated:String
}


type Query{
    mySavedItems:[SavedItem]!
    savedItem(id:ID!):SavedItem!

}

type Mutation{
    saveItem(input:newItemInput!):SavedItem!,
    removeItem(id:ID!):SavedItem!,
    emptySavedItem(user_id:ID!):SavedItem!,
    
}